---
title: "Aggregates in R"
output: html_notebook
---

```{r message = FALSE, error=TRUE}
# load packages
library(readr)
library(dplyr)
```

```{r message = FALSE, error=TRUE}
# load ad clicks data
ad_clicks <- read_csv("ad_clicks.csv")
```

```{r error=TRUE}
# inspect ad_clicks here:
head(ad_clicks)
```

```{r error=TRUE}
# define views_by_utm here:
ad_clicks %>% 
            group_by(utm_source) %>%
            summarize(views_by_utm = n())

```

```{r error=TRUE}
# define clicks_by_utm here:
clicks_by_utm <- ad_clicks %>% 
                      group_by(utm_source, ad_clicked) %>%
                      summarize(count = n())
clicks_by_utm

```

```{r error=TRUE}
# define percentage_by_utm here:
percentage_by_utm <- clicks_by_utm %>% 
                      group_by(utm_source) %>%
                      mutate(percentage = count/sum(count))
percentage_by_utm
```

```{r error=TRUE}
# define experiment_split here:
percentage_by_utm <- percentage_by_utm %>% 
                            filter( ad_clicked == 'TRUE')
percentage_by_utm

```

```{r error=TRUE}
# define clicks_by_experiment here:
experiment_split <- ad_clicks %>%
                      group_by(experimental_group) %>%
                      summarize(count = n())
experiment_split                     

```

```{r error=TRUE}
# define a_clicks here:
clicks_by_experiment <- ad_clicks %>% 
                        group_by(experimental_group) %>% 
                        filter(ad_clicked == "TRUE") %>%
                        summarize(count = n())
clicks_by_experiment


# define b_clicks here:
a_clicks <- ad_clicks %>% 
                filter(experimental_group == "A")
a_clicks
b_clicks <- ad_clicks %>% 
                filter(experimental_group == "B")
```

```{r error=TRUE}
# define a_clicks_by_day here:
a_clicks_by_day <- a_clicks %>%
                  group_by(day,ad_clicked) %>%
                  summarize(count = n())
a_clicks_by_day
b_clicks_by_day <- b_clicks %>%
                  group_by(day,ad_clicked) %>%
                  summarize(count = n())
b_clicks_by_day


# define b_clicks_by_day here:
a_percentage_by_day <- a_clicks_by_day %>% 
                        mutate(percentage = count/sum(count))
a_percentage_by_day

b_percentage_by_day <- b_clicks_by_day %>% 
                        mutate(percentage = count/sum(count))
b_percentage_by_day
```

```{r error=TRUE}
# define a_percentage_by_day here:
a_percentage_by_day <- a_percentage_by_day  %>%
                        filter(ad_clicked == "TRUE")
a_percentage_by_day
b_percentage_by_day <- b_percentage_by_day  %>%
                        filter(ad_clicked == "TRUE")
b_percentage_by_day



# define b_percentage_by_day here:





```